#!/usr/bin/env python3
"""
hunchly-maltego CLI

Commands:
  configure   Auto-detect HunchlyAPI, generate local .mtz, print next steps
  serve       Start the remote transform development server
  check       Verify HunchlyAPI is reachable and working
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def _get_resources_dir() -> Path:
    """Return the path to the bundled resources directory."""
    return Path(__file__).resolve().parent / "resources"


def _merge_resources_into_mtz(mtz_path: Path) -> None:
    """
    Open the .mtz (which is a zip) generated by maltego-trx and inject
    the bundled Hunchly entity definitions, icons, category, machine,
    and transform set that write_local_mtz() doesn't know about.
    """
    import zipfile

    resources = _get_resources_dir()
    if not resources.is_dir():
        print(f"  ⚠ Resources directory not found at {resources} — entities will be missing.")
        return

    with zipfile.ZipFile(mtz_path, "a") as zf:
        existing = set(zf.namelist())

        for file_path in sorted(resources.rglob("*")):
            if file_path.is_dir():
                continue
            # Compute the archive name relative to resources/
            arc_name = str(file_path.relative_to(resources))
            if arc_name not in existing:
                zf.write(file_path, arc_name)

    print("  ✓ Merged entities, icons, category, machine, and transform set")


def cmd_configure(args: argparse.Namespace) -> None:
    """Generate local.mtz and validate the environment."""
    from hunchly_maltego.config import detect_api_path, HunchlyAPINotFoundError
    from hunchly_maltego.extensions import registry

    # 1. Detect HunchlyAPI
    print("─── Detecting HunchlyAPI ───")
    try:
        api_path = detect_api_path()
        print(f"  ✓ Found: {api_path}")
    except HunchlyAPINotFoundError as exc:
        print(f"  ✗ {exc}", file=sys.stderr)
        print()
        print("You can still generate the .mtz — transforms will look for")
        print("HunchlyAPI at runtime via HUNCHLY_API_PATH.")
        api_path = None

    # 2. Generate transforms-only .mtz via maltego-trx
    out_path = Path(args.output).resolve()
    print()
    print("─── Generating .mtz ───")

    try:
        project_dir = str(Path(__file__).resolve().parent)
        command = sys.executable  # Use the current venv Python

        registry.write_local_mtz(
            mtz_path=str(out_path),
            working_dir=project_dir,
            command=command,
            params="project.py",
            debug=True,
        )
        print(f"  ✓ Generated transform configs: {out_path}")
    except Exception as exc:
        print(f"  ✗ Failed to generate .mtz: {exc}", file=sys.stderr)
        print("  Falling back: you can manually import transforms via the remote server.")
        return

    # 3. Merge in entities, icons, category, machine, transform set
    try:
        _merge_resources_into_mtz(out_path)
    except Exception as exc:
        print(f"  ⚠ Failed to merge resources: {exc}")
        print("  The .mtz will have transforms but no entity definitions.")
        print("  You can import the original hunchlyconfiguration.mtz for entities.")

    # 4. Next steps
    print()
    print("─── Next Steps ───")
    print(f"  1. Open Maltego → Import → Configuration → select {out_path.name}")
    print("  2. All transform paths and entities are pre-configured!")
    if api_path is None:
        print("  3. Set HUNCHLY_API_PATH before running transforms:")
        print("       export HUNCHLY_API_PATH=/path/to/HunchlyAPI")
    print()
    print("  For remote/shared deployment instead:")
    print("    hunchly-maltego serve")
    print("    Then configure a TDS in Maltego pointing at http://localhost:8080")


def cmd_serve(args: argparse.Namespace) -> None:
    """Start the transform development server."""
    print(f"Starting Hunchly transform server on port {args.port}...")
    print(f"  Local:  http://localhost:{args.port}")
    print(f"  Seed:   http://localhost:{args.port}/run/hunchly")
    print()
    print("For production, use gunicorn:")
    print(f"  gunicorn --bind=0.0.0.0:{args.port} --threads=25 --workers=2 hunchly_maltego.project:application")
    print()

    from hunchly_maltego.project import app
    app.run(host=args.host, port=args.port, debug=args.debug)


def cmd_check(args: argparse.Namespace) -> None:
    """Verify HunchlyAPI is reachable."""
    from hunchly_maltego.config import detect_api_path, HunchlyAPINotFoundError
    import subprocess

    try:
        api_path = detect_api_path()
        print(f"✓ HunchlyAPI found: {api_path}")
    except HunchlyAPINotFoundError as exc:
        print(f"✗ {exc}", file=sys.stderr)
        sys.exit(1)

    # Try running it with --version or similar to verify it executes
    try:
        proc = subprocess.run([api_path, "--version"], capture_output=True, text=True, timeout=10)
        if proc.returncode == 0:
            print(f"✓ HunchlyAPI responds: {proc.stdout.strip()}")
        else:
            print(f"⚠ HunchlyAPI exited with code {proc.returncode} (may be normal — some builds lack --version)")
    except FileNotFoundError:
        print("✗ Binary exists but is not executable. Check permissions.")
        sys.exit(1)
    except subprocess.TimeoutExpired:
        print("⚠ HunchlyAPI timed out (may need Hunchly running in the background)")
    except Exception as exc:
        print(f"⚠ Could not execute HunchlyAPI: {exc}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="hunchly-maltego",
        description="Hunchly Maltego Transforms — setup, serve, and manage",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # configure
    p_conf = sub.add_parser("configure", help="Auto-detect API, generate local .mtz")
    p_conf.add_argument(
        "-o", "--output",
        default="./hunchly-local.mtz",
        help="Output path for the .mtz file (default: ./hunchly-local.mtz)",
    )
    p_conf.set_defaults(func=cmd_configure)

    # serve
    p_serve = sub.add_parser("serve", help="Start the remote transform server")
    p_serve.add_argument("--host", default="0.0.0.0", help="Bind address (default: 0.0.0.0)")
    p_serve.add_argument("--port", type=int, default=8080, help="Port (default: 8080)")
    p_serve.add_argument("--debug", action="store_true", default=True, help="Enable debug/auto-reload")
    p_serve.set_defaults(func=cmd_serve)

    # check
    p_check = sub.add_parser("check", help="Verify HunchlyAPI is reachable")
    p_check.set_defaults(func=cmd_check)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
